server:
  port: 8092
spring:
  application:
    name: springboot-dubbo-service

dubbo:
  application:
    name: springboot-dubbo-service
  scan:
    base-packages: com.japhone.demo.dubbo.service
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://172.16.87.133:2181